name: Auto trigger PR close

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
    auto-cancel:
        runs-on: ubuntu-latest
        steps:
        - name: Secrets Test
          run: |
            echo ${{ secrets.GITHUB_TOKEN }}

    confirm-run:    
        runs-on: ubuntu-latest
        steps:
        - name: Confirm workflow run
          run: |
            echo "${{ toJson(github.event) }}"
            echo "This workflow has sucessfully run on the closure of the PR!"
            echo "Date and time of run: $(date)"
