name: Auto trigger PR close

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
    # output a few lines to confirm that this workflow was triggered
    confirm:
        name: "Confirm workflow run"
        runs-on: ubuntu-latest
        # print the event payload to the log
        steps:
            - name: Print Event
              run: |
                echo "${{ toJson(github.event) }}"
                echo "This workflow has sucessfully run on the closure of the PR!"
                echo "Date and time of run: $(date)"
