name: Finished Workflow Trigger Test

on:
    pull_request_target:
        types:
          - closed
    workflow_run:
      workflows:
        - Pull Request Workflow
      types:
        - completed

jobs:

    test:
        runs-on: ubuntu-latest
        steps:
        - name: Print Event
          run: |
            echo "This workflow has sucessfully run on the completion of the PR Workflow!"
            echo "Date and time of run: $(date)"
