# This is a basic workflow that is manually triggered

# Display name of workflow
name: Basic Workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'Daniel'
        # Input has to be provided for the workflow to run
        required: true
        type: string
      city:
        description: "Favorite city"
        required: true
        default: "Tupelo"
        type: choice
        options:
        - Slough
        - London
        - Perth
        - Saigon

      fav-color-blue:
        description: "Is your favorite color blue"
        required: true
        type: boolean

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on, in this case a Linus hosted runner
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Runs a single command using the runners shell
    - name: Send greeting
      run: |
        echo "Hello ${{ github.event.inputs.name }}" 
        echo "Your favorite city is ${{ github.event.inputs.city }}"
        echo "Is your favorite color blue: ${{ github.event.inputs.fav-color-blue }}"
    # write the output to a new txt file, along with the date and time of the run
    - name: Write to file
      run: |
        echo "Hello ${{ github.event.inputs.name }}" >> output.txt
        echo "Your favorite city is ${{ github.event.inputs.city }}" >> output.txt
        echo "Is your favorite color blue: ${{ github.event.inputs.fav-color-blue }}" >> output.txt
        echo "Date and time of run: $(date)" >> output.txt

    # Upload the action-output.txt file to the root of the repo
    - name: Upload a file
      uses: actions/upload-artifact@v2
      with:
        name: actions-output.txt
        path: actions-output.txt
