# Name of workflow 
name: Pull Request Workflow

# Workflow trigger event. We want the workflow to trigger on a pull
# request to main
on:
  pull_request:
    branches: 
      - main
  
jobs:

  # Build and test the PR
  build-test-branch:

    name: "Build and Test Of PR"

    runs-on: ubuntu-latest

    steps:
   
    - uses: actions/checkout@v2

    - name: Set default identity
      run: |
        git config --global user.email USER_EMAIL
        git config --global user.name USER_EMAIL

    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Confirm identity
      run: |
        echo "User email: $(git config --global user.email)"
        echo "User name: $(git config --global user.name)"
  
    # Runs a single command using the runners shell
    - name: Send greeting
      run: |
        echo "Date and time of run: $(date)"
        echo "Hello ${{ github.event.inputs.name }}"