name: Testing IF

on:
  workflow_dispatch:

jobs:
    check_runner:
        runs-on: ubuntu-latest
        name: Check runner status
        outputs:
          status: ${{ steps.set-runner-status.outputs.status }}
        steps:
          - name: Check self-hosted runner status
            id: set-runner-status
            run: |
              status=$(echo "online")
              echo "::set-output name=status::$status"
              # echo "status=status" >> $GITHUB_OUTPUT
              echo "Determined Runner Status: $status"
        

    qa:
      runs-on: ubuntu-latest
      name: Trigger QA automation
      needs: check_runner
      steps:
        - name: Trigger QA automation
          run: |
            echo "The output of the check_runner job is: ${{ needs.check_runner.outputs.status }}"
            if [[ "${{contains(needs.check_runner.outputs.status, 'online')}}" == "true" ]]; then
              echo "Trigger QA automation sucess!"
            else
              echo "Trigger QA automation failed!"
            fi

    qa_v2:
      runs-on: ubuntu-latest
      name: Trigger QA automation 2
      needs: check_runner
      if: contains(needs.check_runner.outputs.status, 'online')
      steps:
        - name: Trigger QA automation 2
          run: |
            echo "The output of the check_runner job is: ${{ needs.check_runner.outputs.status }}"
            echo "Trigger QA automation success!"