name: Test My Custom Action

on:
  workflow_dispatch:
    inputs:
        want-to-hear-a-joke:
            description: 'Do you want to hear a joke?'
            required: true
            type: boolean
            default: true


jobs:

  test-action:
    
    runs-on: ubuntu-latest

    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - id: myjoke
        uses: mickeygoussetorg/get-a-dad-joke@v1
        
      - name: Output Dad Joke
        run: echo "${{ steps.myjoke.outputs.dad-joke }}"

  create-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: myjoke
        uses: mickeygoussetorg/get-a-dad-joke@v1

      - name: Create Issue
        uses: actions/github-script@v4
        with:
          script: |
            const { data } = await github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'New issue created from workflow',
              body: 'This issue was created automatically from a workflow! Here's your dad joke: ${{ steps.myjoke.outputs.dad-joke }}',
            });
            console.log(`Created issue ${data.html_url}`);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}