name: Test Path Exclusions

on:
    push:
        paths-ignore:
            - 'db/migrate/*'
    pull_request:
        paths-ignore:
            - 'db/migrate/*'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Test
              run: echo "Test run for ${{ github.event_name }} succeeded"

            - name: 'Execute vDMC-CI Status'
              if: ${{ always() }}
              run: sfci status --debug
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                TEAMS_WEBHOOK: ${{secrets.TEAMS_WEBHOOK}}