name: Test Path Exclusions

# This workflow will only run for pushes and PRs that are made in any directory except db/migrate

on:
    push:
        paths-ignore:
            - 'db/migrate/*'
    pull_request:
        paths-ignore:
            - 'db/migrate/*'

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Test
              run: echo "Test run for ${{ github.event_name }} succeeded"