name: Test My Custom Action

on:
    push:
      branches:
        - main

#   workflow_dispatch:
#     inputs:
#         want-to-hear-a-joke:
#             description: 'Do you want to hear a joke?'
#             required: true
#             type: boolean
#             default: true

jobs:

  test-action:
    
    runs-on: ubuntu-latest

    
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - id: myjoke
        uses: mickeygoussetorg/get-a-dad-joke@v1
        
      - name: Output Dad Joke
        run: echo "${{ steps.myjoke.outputs.dad-joke }}"

  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Set default identity
        run: |
          git config --global user.email ${{ vars.USER_EMAIL }}
          git config --global user.name ${{ vars.USER_NAME }}

      - uses: actions/checkout@v3

      - id: myjoke
        uses: mickeygoussetorg/get-a-dad-joke@v1

      - name: Create Issue
        uses: actions/github-script@v4
        with:
          script: |
            # create an issue
            github.issues.create({
              repo: context.repo.repo,
              owner: context.repo.owner,
              title: 'Dad Joke',
              body: ${{ steps.myjoke.outputs.dad-joke }}
            })
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}