name: Test My Custom Action

on:
    push:
      branches:
        - main

    workflow_run:
      workflows: [Basic Workflow]
      types:
        - completed

jobs:
    # use this: https://docs.github.com/en/actions/managing-issues-and-pull-requests/scheduling-issue-creation
    
  create-issue:
    name: Create Issue
    runs-on: ubuntu-latest
    permissions:
        issues: write
    
    steps:
      - name: Set default identity
        run: |
          git config --global user.email ${{ vars.USER_EMAIL }}
          git config --global user.name ${{ vars.USER_NAME }}

      - name: Get Dad Joke
        id: myjoke
        uses: mickeygoussetorg/get-a-dad-joke@v1

      - name: Create a Dad Joke Issue
        uses: imjohnbo/issue-bot@v3
        with:
            assignees: "danielhardej"
            title: "Dad Joke"
            body: | 
              # Dad Jokes are no laughing matter

              ### Here's a dad joke for you:
                
                ${{ steps.myjoke.outputs.dad-joke }}

              Did you read it?
               - [ ] Yes
               - [ ] No
            
            close-previous: false

        env:
            GITHUB_TOKEN: ${{ secrets.GH_PAT }}

        
